### ISSUE TITLE
Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by DailyLollipops** [joergmlpts/bpm_bt#2]
Hello, I've running this on my Windows 10 machine and it works fine, however when I tried running it on my Raspberry Pi 4B machine. It got an error that says
```
Exception: Task <Task pending name='Task-5' coro=<Event.wait() running at /usr/lib/python3.9/asyncio/locks.py:226> cb=[_release_waiter(<Future pendi...f80b8d0d0>()]>)() at /usr/lib/python3.9/asyncio/tasks.py:416]> got Future <Future pending> attached to a different loop
```

Any idea why this is happening?

**Comment by joergmlpts** [comment]
Maybe revert this change for Python 3.10; it was about event loops: [fix for 'DeprecationWarning: There is no current event loop' in Python 3.10](https://github.com/joergmlpts/blood-pressure-monitor/commit/07f27ad95ec8907f827a53c1467e7038004cce38). Then try again with Python 3.9 on Raspberry.

**Comment by DailyLollipops** [comment]
It now works thanks for you help

I may need to mention this but I found out its possible to pair again in case you've lost the encryption key but will lose all data in the blood pressure monitor because it needs to be reset
To reset, just press then start button until the bluetooth icon flash and press the time logo part at the upper part

Anyways, it has been a great help thank you

**Comment by joergmlpts** [comment]
Thanks for the tip! I did not know how to reset the unit.
